export const ENUM_TABLES = {
  CUSTOMERS: 'customers'
}

export const CURRENT_USER_COOKIE = 'CURRENT_USER_COOKIE'
export const SUPABASE_ACCESS_TOKEN_COOKIE = 'SUPABASE_ACCESS_TOKEN'
export const SUPABASE_REFRESH_TOKEN_COOKIE = 'SUPABASE_REFRESH_TOKEN'
